=== hunnor-dict/export-ant/tester/context/simple-html.dtd
<!ELEMENT dictionary (letter*)>
<!ATTLIST dictionary
    updated CDATA #REQUIRED>

<!ELEMENT letter (entry*)>
<!ATTLIST letter
    label CDATA #REQUIRED>

<!ELEMENT entry (forms*, inflections*, forms-html?, translations-html?)>
<!ATTLIST entry
    id CDATA #REQUIRED>

<!ELEMENT forms (form*)>

<!ELEMENT form (#PCDATA)>
<!ATTLIST form
    n CDATA #IMPLIED>

<!ELEMENT inflections (inflection*)>

<!ELEMENT inflection (#PCDATA)>

<!ELEMENT forms-html (#PCDATA | span)*>

<!ELEMENT translations-html (#PCDATA | span)*>

<!ELEMENT span (#PCDATA | span)*>
<!ATTLIST span
    class CDATA #IMPLIED>

=== hunnor-dict/export-ant/tester/context/entry-forms-translations-html.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entry SYSTEM "simple-html.dtd">
<entry id="1">
	<forms>
		<form>w1</form>
	</forms>
	<forms-html><span><span class="form">f1 <span class="pos">f2</span> f3</span></span></forms-html>
	<translations-html><span><span>t1</span> t2 <span class="sense-nr">t3</span></span></translations-html>
</entry>
